Add download function to administration index page
mkapra/dokumentvwsys pull request #129
Opened 2021-06-22 19:49 UTC by adnansh95

2021-06-22 20:00 UTC, mkapra requested changes

2021-06-22 20:00 UTC, mkapra commented on src/dokumentvwsys/app/controllers/administration_controller.rb
> +  def show
Wir müssen hier aufpassen. Das muss durch einen Admin Check gehen. Passiert das?

2021-06-22 20:59 UTC, adnansh95 commented on src/dokumentvwsys/app/controllers/administration_controller.rb
> +  def show
ist schon vorhanden "before_action :verify_admin_user"

2021-06-22 20:59 UTC, adnansh95 commented on src/dokumentvwsys/app/controllers/administration_controller.rb
> +      end
das ist mir noch unklar, ob die Datei überhaupt gespeichert wird

2021-06-23 15:53 UTC, mkapra commented on src/dokumentvwsys/app/controllers/administration_controller.rb
> +      end
Willst du das mal ausprobieren/nachschauen?

2021-06-23 22:01 UTC, merged