Add new login page
mkapra/dokumentvwsys pull request #13
Opened 2021-03-07 14:44 UTC by adnansh95

--- Why is this change necessary?
We need a new wonderful login page

--- How does it address the issue?
Edit the default login page and edit also the application.scss file

2021-03-07 14:46 UTC, mkapra requested changes

2021-03-07 14:46 UTC, mkapra commented on src/dokumentvwsys/app/views/devise/sessions/new.html.erb
> +    </form>
Where is the rails form?

2021-03-07 14:46 UTC, mkapra commented on src/dokumentvwsys/app/assets/stylesheets/application.scss
> +
This is bad. It is for all sites and not only the login site

2021-03-07 14:46 UTC, mkapra commented on .gitignore
> +*~
?

2021-03-07 16:52 UTC, adnansh95 commented on .gitignore
> +*~
to ignore all temp files

2021-03-07 18:46 UTC, mkapra requested changes

2021-03-07 18:46 UTC, mkapra commented on src/dokumentvwsys/app/views/devise/registrations/new.html.erb
> -<h2>Sign up</h2>
I think this heading should stay

2021-03-07 18:46 UTC, mkapra commented on src/dokumentvwsys/app/views/devise/registrations/new.html.erb
> +          <%= f.text_field :username, autofocus: true, autocomplete: "username", class:"form-control" %>
```suggestion
          <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
```

2021-03-07 18:46 UTC, mkapra commented on src/dokumentvwsys/app/views/devise/registrations/new.html.erb
> +          <div class="center_div"><img src="/hi.png" id="icon" alt="User Icon" class: "mx-auto d-block"/></div>
`class: "mx-auto d-block"`
This is a rails specific and will not work here

2021-03-07 18:46 UTC, mkapra commented on src/dokumentvwsys/app/views/devise/sessions/new.html.erb
> +          <div class="center_div"><img src="/hi.png" id="icon" alt="User Icon" class: "mx-auto d-block"/></div>
This image is not centered on an iphone

2021-03-11 20:25 UTC, mkapra approved these changes

2021-03-11 20:42 UTC, merged